# Generated by Django 4.0 on 2022-04-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library_db',
            name='author',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
